### ISSUE TITLE
Segfault in timestamped-socket

### ISSUE THREAD

**Issue by dsseng** [pendulum-project/timestamped-socket#15]
Segfault by null pointer dereference at [src/interface.rs:89:31](https://github.com/pendulum-project/timestamped-socket/blob/fa60ce6b96c70d98f89b89bb2f33cf65a41095a9/src/interface.rs#L89), on both a PC with openSUSE Tumbleweed and Raspberry Pi 5 with Debian 12

**Comment by rnijveld** [comment]
Looks like `ifa_addr` in the ifaddrs struct might be null in some cases (i.e. the interface does not have an address for some reason), which we don't check for.

**Comment by dsseng** [comment]
Yes, it's null as per lldb debug. I couldn't fix that myself because I'm unsure what's the case. Interfaces have both IPv4 and IPv6 addresses.

**Comment by davidv1992** [comment]
Thank you for reporting and triaging this. I have gone over all the unsafe code in the crate again and the linked pull request should fix the issue, as well as provide proper reasoning for why all our unsafe code is valid now. Please let us know if you find any further issues.
